PROJECT: 'gtppo_tr_jaad_intention'
CKPT_DIR: 'checkpoints/JAAD_checkpoints/gtppo_tr_checkpoints/' 
OUT_DIR: 'outputs/JAAD_outputs/gtppo_tr_outputs'
DEVICE: 'cuda'
METHOD: 'GtppoTR'
VISUALIZE: False
USE_WANDB: False
MODEL:
  PRED_INTENTION: True
  ENC_WITH_ATTENTION: True # whether to use soft attention in the encoder

  IMG_SIZE: (256,256)
  BEST_OF_MANY: True
  K: 20
  LATENT_DIST: 'gaussian' 
  LATENT_DIM: 32 

  PRED_LEN: 45 # input and pred_len is defined in 30FPS
  GLOBAL_EMBED_SIZE: 256
  GLOBAL_HIDDEN_SIZE:  256
  GLOBAL_INPUT_DIM: 4
  DROPOUT: 0.0

  WITH_FLOW: False
  ENC_CONCAT_TYPE: 'average'
  INPUT_EMBED_SIZE: 256
  FLOW_EMBED_SIZE: 256
  FLOW_HIDDEN_SIZE: 256
  ENC_HIDDEN_SIZE: 256
  DEC_INPUT_SIZE: 256
  DEC_HIDDEN_SIZE: 256
  DEC_OUTPUT_DIM: 4
DATASET:
  NAME: 'JAAD'
  ROOT: 'path-to-jaad-dataset'
  TRAJECTORY_PATH: 'path-to-jaad-dataset/trajectories'
  BBOX_TYPE: 'cxcywh' # bbox is in cxcywh format
  NORMALIZE: 'zero-one' 
  MIN_BBOX: [0,0,0,0] # the min of cxcywh or x1x2y1y2
  MAX_BBOX: [1920, 1080, 1920, 1080] # the max of cxcywh or x1x2y1y2
DATALOADER:
  NUM_WORKERS: 0 # when not 0, will cause two time slower in windows system
SOLVER:
  MAX_EPOCH: 50
  BATCH_SIZE: 128
  LR: 0.001
  scheduler: 'plateau'
TEST:
  BATCH_SIZE: 1024